menu:
  é¦–é¡µ: / || fas fa-home
  å½’æ¡£: /archives/ || fas fa-archive
  æ ‡ç­¾: /tags/ || fas fa-tags
  # åˆ†ç±»: /categories/ || fas fa-folder-open
  å…³äº: /about/ || fas fa-heart

aside:
  enable: true
  hide: false
  button: true
  mobile: true # æ‰‹æ©Ÿé é¢ï¼ˆ é¡¯ç¤ºå¯¬åº¦ < 768px ï¼‰æ˜¯å¦é¡¯ç¤ºasideå…§å®¹
  position: right # left or right
  archives: true
  card_author:
    enable: true
    description:
    button:
      enable: true
	    icon: fab fa-github
      text: Github
      link: https://github.com/zsStrike
  card_announcement:
    enable: false
    content: This is my Blog
  card_recent_post:
    enable: false
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories:
    enable: false
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true    
  card_archives:
    enable: false
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYYå¹´MMæœˆ
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all

local_search:
  enable: true
  preload: false
  CDN:

# ç¾åŒ–é é¢é¡¯ç¤º
beautify:
  enable: false
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"

wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# medium_zoom: true
instantpage: true

# https://github.com/vinta/pangu.js
# Insert a space between Chinese character and English character (ä¸­è‹±æ–‡ä¹‹é–“æ·»åŠ ç©ºæ ¼)
pangu:
  enable: false
  field: post # site/post

highlight_theme: mac light
highlight_copy: true
highlight_shrink: false
highlight_lang: true

disable_top_img: true

favicon: /assets/avatar.jpg

cover:
  # æ˜¯å¦é¡¯ç¤ºæ–‡ç« å°é¢
  index_enable: false
  aside_enable: false
  archives_enable: false
  # å°é¢é¡¯ç¤ºçš„ä½ç½®
  # ä¸‰å€‹å€¼å¯é…ç½® left , right , both
  position: both
  # ç•¶æ²’æœ‰è¨­ç½®coveræ™‚ï¼Œé»˜èªçš„å°é¢é¡¯ç¤º
  default_cover:
    - /assets/default_cover.png

# Replace Broken Images (æ›¿æ›ç„¡æ³•é¡¯ç¤ºçš„åœ–ç‰‡)
error_img:
  flink: /assets/default_cover.png
  post_page: /assets/default_cover.png

# Related Articles
related_post:
  enable: false
  limit: 6 # Number of posts displayed
  date_type: created # or created or updated æ–‡ç« æ—¥æœŸé¡¯ç¤ºå‰µå»ºæ—¥æˆ–è€…æ›´æ–°æ—¥

post_pagination: false

post_meta:
  page:
    date_type: both # created or updated or both ä¸»é æ–‡ç« æ—¥æœŸæ˜¯å‰µå»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½é¡¯ç¤º
    date_format: relative # date/relative é¡¯ç¤ºæ—¥æœŸé‚„æ˜¯ç›¸å°æ—¥æœŸ
    categories: false # true or false ä¸»é æ˜¯å¦é¡¯ç¤ºåˆ†é¡
    tags: true # true or false ä¸»é æ˜¯å¦é¡¯ç¤ºæ¨™ç±¤
    label: true # true or false é¡¯ç¤ºæè¿°æ€§æ–‡å­—
  post:
    date_type: both # created or updated or both æ–‡ç« é æ—¥æœŸæ˜¯å‰µå»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½é¡¯ç¤º
    date_format: relative # date/relative é¡¯ç¤ºæ—¥æœŸé‚„æ˜¯ç›¸å°æ—¥æœŸ
    categories: false # true or false æ–‡ç« é æ˜¯å¦é¡¯ç¤ºåˆ†é¡
    tags: true # true or false æ–‡ç« é æ˜¯å¦é¡¯ç¤ºæ¨™ç±¤
    label: true # true or false é¡¯ç¤ºæè¿°æ€§æ–‡å­—

post_copyright:
  enable: true
  decode: true
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

avatar:
  img: /assets/avatar.jpg
  effect: false # é ­åƒæœƒä¸€ç›´è½‰åœˆ

photofigcaption: false

# copy settings
# copyright: Add the copyright information after copied content (è¤‡è£½çš„å…§å®¹å¾Œé¢åŠ ä¸Šç‰ˆæ¬Šä¿¡æ¯)
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 5000

footer:
  owner:
    enable: true
    since: 2017

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

runtimeshow:
  enable: true
  publish_date: 6/7/2017 00:00:00  
  ##ç¶²é é–‹é€šæ™‚é–“
  #æ ¼å¼: æœˆ/æ—¥/å¹´ æ™‚é–“
  #ä¹Ÿå¯ä»¥å¯«æˆ å¹´/æœˆ/æ—¥ æ™‚é–“

# social:
#   fab fa-github: https://github.com/zsStrike || Github
#   fas fa-envelope: mailto: 2439758713@qq.com || Email


mathjax:
  enable: true
  # true è¡¨ç¤ºæ¯ä¸€é éƒ½åŠ è¼‰mathjax.js
  # false éœ€è¦æ™‚åŠ è¼‰ï¼Œé ˆåœ¨ä½¿ç”¨çš„Markdown Front-matter åŠ ä¸Š mathjax: true
  per_page: false

# A simple 404 page
error_404:
  enable: true
  subtitle: "é¡µé¢èµ°ä¸¢äº†ğŸ˜­"
  background: /assets/404.png